typography_spectrum: 0.60765
color:
  brandColors:
    - '#00226c'
    - '#eb722b'
    - '#7487af'
    - '#f7f8fa'
    - '#b8c0d4'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63308
analytics:
  google: null
  facebook: null
  twitter: null
name: netnotix
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: netnotix
description: is testing the grid
purpose: []
