name: null
favicon: null
layout_spectrum: 0.63308
typography_spectrum: 0.60765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00226c'
    - '#eb722b'
    - '#7487af'
    - '#f7f8fa'
    - '#b8c0d4'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: awareness
    item: null
    url: null
